[versions]
junit = "6.0.0"

[libraries]
annotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
