[versions]
junit = "5.10.4"

[libraries]
annotations = { module = "org.jetbrains:annotations", version = "25.0.0" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
